// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "TS_NODE_TRANSPILE_ONLY=1 node --max-old-space-size=512 -r ts-node/register/transpile-only -r tsconfig-paths/register prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
